kowalski:
  protocol: "https"
  host: "kowalski.caltech.edu"
  port: 443
  username:
  password:

irsa:
  url: "https://irsa.ipac.caltech.edu/ibe/data/ztf/products/"
  url_login: "https://irsa.ipac.caltech.edu/account/signon/login.do"
  username: anonymous
  password: anonymous
