name: test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-watchdog:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.8'
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: '3.8'
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.36.0
          conda install -c conda-forge astromatic-swarp
          python setup.py install
      - name: Set up configs
        shell: bash -l {0}
        run: |
          cd scripts
          python run_tails.py run
            --config=../config.defaults.yaml
            --checkpoint=../models/tails-20210107/tails
            --score_threshold=0.5
            --cleanup=none
            --single_image=ztf_20191014495961_000570_zr_c05_o_q3
          ls runs
