name: test-run-tails

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-run-tails:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          python-version: '3.8'
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.36.0
          conda install -c conda-forge astromatic-swarp
          python setup.py install
          pip install -r requirements.txt
      - name: Fetch models
        shell: bash -l {0}
        run: |
          mkdir models
          gsutil -m cp -r -n gs://tails-models/* models/
      - name: Run inference on a publicly-available ZTF observation of 2I/Borisov
        shell: bash -l {0}
        run: |
          cd tests
          cp ../scripts/run_tails.py .
          python -m pytest -s test_run_tails.py
